### ISSUE TITLE
Add Jupyter-HPC mailing list link.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter.github.io#174]
@minrk created this list. We have a nice icon for the classic ML and the education one. 
Should we get a nice icon for HPC ?

**Comment by minrk** [comment]
That would be nice!

**Comment by cameronoelsen** [comment]
@Carreau @minrk Just wondering, what is the Jupyter HPC mailing list? I am not sure what the abbreviation represents (also where is this kept?). I can add this to the resources page!

**Comment by minrk** [comment]
HPC is high-performance computing. The list is [here](https://groups.google.com/forum/#!forum/jupyter-hpc). It was created after a meeting with some HPC participants, but hasn't had any activity (literally zero posts, in part because Google Groups borked the setup, so it didn't work for the first few days). At this point, I'm not sure we should have created it, instead using the regular Jupyter list for such communications. It does have quite a few members, though, despite zero posts.

**Comment by Carreau** [comment]
I would suggest sending an email to the mailing list, saying it never had any activity and closing it. (not deleting but blocking everyone and preventing new people to subscribe). Don't know if you can "Hide" a google group.

**Comment by palewire** [comment]
Since this ticket has been inactive for four years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
