### ISSUE TITLE
Remove dropdown from #177 (New documentation experience).

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter.github.io#207]
While the big button looks nice, hiding documentation in submenus make some documentation impossible to discover without clicking everywhere. 

just form the top of your head if you are a new contributor:
 - Where is the doc for Jupyter_core ?  Architecture  or deployment ? 
 - What's the difference between jupyterHub and Deployment ? 
 - Why is Lab not in `Interfaces` it's only an interface AFAICT. 

My take on that is to expand the dropdown by default So that user can easily find the project they are looking for instead of having to click 9 categories.

**Comment by willingc** [comment]
Let's look at these categories with Brian next week. There's a few things that we should swap around from submenus. There were some design elements from Matlab and Apple docs that this was targeting. We should make the new contributor comfortable from the start. 

@cameronoelsen @charnpreetsingh Let's think about a block which will support access to all projects by name (A to Z) or context search. @Carreau I'm going to assign myself for now so it doesn't fall off my radar.

**Comment by Carreau** [comment]
Even if we fix categories, I think that having submenus hidden by default is the wrong choice. 
Or at least there should be : 
  - Either more indication that there are submenues
  - Or More top level direct access to some categories.

**Comment by charnpreetsingh** [comment]
@willingc Will you be around next week or will you be at the dev meeting?

**Comment by willingc** [comment]
Hi @charnpreetsingh, I'll be at the dev meeting but we can try to have a call with Brian. Would you and @cameronoelsen brainstorm some options for a visual indicator for a submenu (perhaps in the lower right corner of each category box). Thanks!

**Comment by charnpreetsingh** [comment]
@willingc Sounds good, I will work with him on some ideas.

**Comment by ellisonbg** [comment]
The idea for these dropdowns came from the Mathematica Documentation, which is the best large scale technical language documentation I have ever seen:

http://reference.wolfram.com/language/

Some of the important points:

* Within 2-3 clicks you can end up looking at exactly what you want - it is really spectacular in this respect and I encourage you to play with it.
* The documentation is organized around what the user is trying to do, rather than how Mathematica is written and organized as a code base.
* They spent a significant effort/time working on how to organize their content into a clean hierarchy.
* You can't pull that off without significant user testing of the information architecture. 

Our intent with the documentation landing page and the Sphinx theme redesign is to set the visual design. But for everything to work, we will have to follow up with a very significant information/content reorganization (hence the hiring of the technical writer). I have started to gather resources and approaches for organizing large scale content to help us approach that in a systematic manner. One of the main pushes I would like to make in that reorganization is to begin organizing our documentation not around repos (which users don't care/know about) to a set of cleanly organize hierarchical topics. A great example would be a general area like this:

* Working with Notebook Documents
  - Converting notebooks to other formats
  - The Notebook document format
  - Notebook metadata
 
A user wouldn't know or care that these three topics span many different repos (nbformat, nbconvert, notebook, jupyterlab).

I agree that the *current* organization of the cards and submenus is confusing. I basically told @cameronoelsen "make something up for now" and for that level of treatment I think he did a great job. But I fully agree with all the points you made about particular things being in add places though.

The original thinking for hiding content behind dropdowns came from two sources:

1) The efficacy of the Mathematica docs.
2) The idea that too many choices at a given level makes it difficult for a user to find content.

However, a quick search for research in this area shows that 2) might not be justified:

This study found evidence that a flat approach works quite well, but that other hierarchy shapes also work well:

http://www.surl.org/examining-the-effects-of-hypertext-shape-on-user-performance/

This book looks to be highly regarded, but a longer read:

http://www.uis.edu/webservices/wp-content/uploads/sites/8/2013/02/Designing_for_Scent.pdf

**Comment by Carreau** [comment]
But, wolfram have 10 if not more categories per box. Seeing the amount of categories we have I'm going to say that 2 to 3 click is 1 to 2 click too many in most cases. I'm fine with _some_ things being hidden or under a submenu. But let's look at 1 of the wolfram categories:

<img width="938" alt="screen shot 2017-05-27 at 16 02 51" src="https://cloud.githubusercontent.com/assets/335567/26524816/02ecc36c-42f6-11e7-9006-9a677c134ecd.png">

One of this panel could host and link to all the current links we currently have without having to click through N submenus.

Collapsing is useful **when you have too much on screen**. but we don't have too much **yet** so collapsing is adding extra burden on the user.

Most of the studies you link to point to at least testing with 64 elements. Most of the case made are for contents that are more than twice the number of links we have.

**Comment by ellisonbg** [comment]
Yep, we may not have enough links that the nested approach is needed. However, that isn't completely obvious to me that we won't end up with 50-100 secondary level topics. I think we should proceed with the information architecture design (what our appropriate top-level, secondary, tertiary topics) and let that determine what type of UI is appropriate. If the number of secondary topics is reasonable I am fine removing the dropdowns. Also fine with doing some redesign in the meantime to expand this content.

**Comment by Carreau** [comment]
> Yep, we may not have enough links that the nested approach is needed. However, that isn't completely obvious to me that we won't end up with 50-100 secondary level topics. I think we should proceed with the information architecture design (what our appropriate top-level, secondary, tertiary topics) and let that determine what type of UI is appropriate. If the number of secondary topics is reasonable I am fine removing the dropdowns. Also fine with doing some redesign in the meantime to expand this content.

That seem like a good plan. I agree that if number of links increase menus are necessary. But if possible promoting things to top level would be great !

Thanks !

**Comment by willingc** [comment]
@ellisonbg @Carreau Let's discuss at the team meeting. I wonder if we could combine the Education block with JupyterHub since right now only nbgrader is under education. That would free up a block to use as `A to Z projects` where all the projects could be accessed if the block is clicked.

**Comment by palewire** [comment]
Since this ticket has been inactive for three years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
