### ISSUE TITLE
Update Community Page

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter.github.io#382]
Add better descriptions for GitHub (issues for bugs and regressions) and Discourse (Community Technical Support)

See https://github.com/jupyter/nbconvert/issues/1376#issuecomment-691522512 and https://github.com/jupyter/nbconvert/pull/1377 for suggested wording

**Comment by choldgraf** [comment]
I wonder if this would be an addition somewhere around here: https://jupyter.readthedocs.io/en/latest/use/using.html ? A "Need help?" section like the ones that you added to nbconvert?

**Comment by willingc** [comment]
We should probably update all repos. After you are back from paternity leave, I would recommend we do that and move most of the docs to MyST too.

**Comment by choldgraf** [comment]
The nice thing about MyST is that we can have rST and MyST markdown co-exist, so it can be a migratory process rather than a total re-write all at once.

Maybe we can start by creating an issue that lists a few pilot repos to migrate to MyST and folks can work to convert them over to MyST markdown over time. Then depending on how that experience goes, decide whether to do the same for other repositories. What do you think?

**Comment by palewire** [comment]
Since this ticket has gone more than a year without any activity, I'm going to close it.
