### ISSUE TITLE
Should the Install page recommend the JupyterLab Desktop App?

### ISSUE THREAD

**Issue by palewire** [jupyter/jupyter.github.io#589]
https://blog.jupyter.org/jupyterlab-desktop-app-now-available-b8b661b17e9a
https://github.com/jupyterlab/jupyterlab-desktop

**Comment by krassowski** [comment]
Yes, but not yet. I explained it in https://github.com/jupyterlab/jupyterlab-desktop/issues/275#issuecomment-932965793. Currently installation will prompt because the installer is not signed (see https://github.com/jupyterlab/jupyterlab-desktop/pull/318 and https://github.com/jupyterlab/jupyterlab-desktop/issues/202). We are still modernising the app and I hope we will be able to promote it on the main site soon... My hope is by February when it comes to the things I am working on, but I do not work on code signing - for ETA that on that I would ask @mbektas.

**Comment by palewire** [comment]
Thank you.
