### ISSUE TITLE
Dedicated JupyterDay Page

### ISSUE THREAD

**Issue by cameronoelsen** [jupyter/jupyter.github.io#66]
So after drafting up a few solutions to creating a dedicated JupyterDay page, I came up with the page below. Not sure if we need this page yet, seeing that there aren't many meetups happening yet, but while there aren't many happening I can start building it so we can push it whenever necessary. Just feel it may get tedious to scroll through the blog when we start having news coming in as well as events planned. Anyway, I designed the page around an open source touch enabled carousel that is, apparently, easy to customize and tailor to your need. It is called "Owl Carousel" and can be found here: http://owlgraphic.com/owlcarousel/index.html#customizing

Users can easily scroll through the event schedule, find the event they will be attending, and the information will appear below. We can also add a button to redirect to an Eventbrite page, or even in the future host the RSVPing through the website.

Overall just wanted to get some feedback and wondering if we want to continue on this idea!
![jupyterday-mockup](https://cloud.githubusercontent.com/assets/6437976/10860525/b9d25e74-7f26-11e5-825b-ae4a34d5f0f2.png)

**Comment by ellisonbg** [comment]
I am +1 on having a JupyterDay page on the website. However, there are
going to be many non-coding people who need to work with this. I am a bit
hesitant for them to have to deal with GitHub to make changes.Because of
that, I think all of the details of each individual JupyterDay should be a
blog post.

Also, a website is horrible at tracking sequeces of date/time events. That
is really much more appropriate for a blog. It would keep a nice time
ordered sequence of all our events. Again, another reason to have each
event on the blog.

We also may end up having multiple events running at the same time. With
this in mind, I think the main JupyterDay page should just link to the blog
posts and maybe haver banners for the upcoming ones.

Thoughts?



On Fri, Oct 30, 2015 at 7:53 PM, Cameron Oelsen <notifications@github.com>
wrote:

> So after drafting up a few solutions to creating a dedicated JupyterDay
> page, I came up with the page below. Not sure if we need this page yet,
> seeing that there aren't many meetups happening yet, but while there aren't
> many happening I can start building it so we can push it whenever
> necessary. Just feel it may get tedious to scroll through the blog when we
> start having news coming in as well as events planned. Anyway, I designed
> the page around an open source touch enabled carousel that is, apparently,
> easy to customize and tailor to your need. It is called "Owl Carousel" and
> can be found here:
> http://owlgraphic.com/owlcarousel/index.html#customizing
>
> Users can easily scroll through the event schedule, find the event they
> will be attending, and the information will appear below. We can also add a
> button to redirect to an Eventbrite page, or even in the future host the
> RSVPing through the website.
>
> Overall just wanted to get some feedback and wondering if we want to
> continue on this idea!
> [image: jupyterday-mockup]
> <https://cloud.githubusercontent.com/assets/6437976/10860525/b9d25e74-7f26-11e5-825b-ae4a34d5f0f2.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/66>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by captainsafia** [comment]
@ellisonbg — I agree with having the actual event pages on a separate platform, whether EventBrite or otherwise.

I do think we can benefit from a JupyterDay section on the website. @cameronoelsen, you can keep most of the elements on the design you made and perhaps we can create a page on our website that contains the information that Katie drafted in the event guide so that members of the community can set up their own JupyterDays, basically a how-to page.

**Comment by palewire** [comment]
Since this ticket has been inactive for six years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
