### ISSUE TITLE
Link to the official YouTube channel from the web site

### ISSUE THREAD

**Issue by JasonWeill** [jupyter/jupyter.github.io#755]
The [YouTube channel](https://www.youtube.com/@ipython) doesn't have "Jupyter" in the name, so some people may be unsure whether it's an official Jupyter presence. Can we have a link to it in the footer, beside our other social media, and/or from the Community page? Thanks!

**Comment by JasonWeill** [comment]
YouTube previously suggested by @Carreau in #257.

**Comment by jtpio** [comment]
> The [YouTube channel](https://www.youtube.com/@ipython) doesn't have "Jupyter" in the name, so some people may be unsure whether it's an official Jupyter presence

Should the handle be updated to `@jupyter` instead of the current `@ipython`?

Someone already seems to be using it: https://www.youtube.com/@jupyter. Maybe we can make a request to YouTube to change that, if possible?

**Comment by JasonWeill** [comment]
Per the governance docs, I can reach out to the trademarks committee (jupyter-trademarks@googlegroups.com) about the case above. None of us should be making such a request on our own.

**Comment by ivanov** [comment]
I took a quick look and it looks like this channel was registered long before Jupyter was a twinkle in anyone's eye. If you click on "About this channel", you'll find out that this person joined May 7, 2006, so that lines up between IPython 0.7.1  and 0.7.2 releases, so it's almost certainly not one we have control over. Jupyter first usage is in July 2014, for reference.

Given that the account has been sitting there idle, I don't expect it's worth pursuing. For example, https://twitter.com/jupyter is also not us, and also was registered in 2009, well before "Jupyter" began being used in lieu of "IPython Notebook".

Personally, I think it make sense if using the "IPython" channel is confusing for Jupyter  users, we could either rename it to "ProjectJupyter" or make a new channel with that name, or something similar.

**Comment by jtpio** [comment]
> Personally, I think it make sense if using the "IPython" channel is confusing for Jupyter users, we could either rename it to "ProjectJupyter" or make a new channel with that name, or something similar.

That sounds good, and it looks like it's still available.

**Comment by lokashrinav** [comment]
Hello. I was interested in this issue and was just curious if the youtube channel name was going to be changed?

**Comment by jtpio** [comment]
The YouTube handle and channel title have now been renamed: https://www.youtube.com/@projectjupyter

![image](https://github.com/jupyter/jupyter.github.io/assets/591645/f7cdaee2-1a87-44ee-89df-f8c56a065e64)

**Comment by Carreau** [comment]
Now I'm a bit confused, as `https://www.youtube.com/ipython` still works. `https://www.youtube.com/@ipython` (which is the link @JasonWeill mentioned at the beginning of this issue) is 404.

I would have expected redirects at least, but I understand this is not under your control. 

We likely need to search for old mentions of the `@ipython/ipython` channel and update the links, searching for it I can find "only"2 mentions: 

```
jupyter/docs/source/community/content-community.rst
28:Some of these meetings are recorded and uploaded to our `YouTube channel <https://www.youtube.com/ipython>`_.

jupyter.github.io/social.md
29:- YouTube: https://youtube.com/@ipython
```
