### ISSUE TITLE
New JupyterHub page

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyter.github.io#94]
We are starting to talk about having a dedicated JupyterHub page on the website. Right now the only mention we have in buried on the home page below the fold. Opening this issue to track progress and design work.

**Comment by ellisonbg** [comment]
Would be helpful if someone could do a problem statement for this to help guide the design process:

Problem Statement

I am: [who, including 3 characteristics]
I am trying to: [outcome/job]
But: [problem/barrier]
Because: [root cause]
Which makes me feel: [emotions]

**Comment by minrk** [comment]
Who should "I am" be referring to? A prospective hub-deployer? If so, here's a shot:

I am: a teacher/professor with linux admin skills or a student assistant / campus support with such skills.
I am trying to: teach a scientific subject with computational work
But: Dealing with software problems on diverse student computers consumes too much time
Because: There are lots of different kinds of computers and ways to install things and many versions of everything
Which makes me feel: 🐌  (I don't know how to deal with this one)

**Comment by ellisonbg** [comment]
The "I am" should be the person we would design this page for - and I think
the person you choose is definitely one of the core people this page should
focus on. There may be multiple such people (or personas as they are called
in a design context) - maybe another one would be an IT person at a company
whose Data Science team told them to install JupyterHub on their cluster.

I will give that one a go:

I am: an experienced IT/sysadmin person that has no idea what JupyterHub is
I am trying to: learn about and install/configure/deploy JupyterHub for my
data science team
But: I can't find any information about JupyterHub on the jupyter website
Because: There isn't much information there and the info that is there is
buried way down a page.
Which makes me feel: a bit sketchy about deploying it

Speaking from experience - I think the "makes me feel" part of your persona
would be "stressed about teaching"

Cheers, Brian

On Tue, May 31, 2016 at 1:07 AM, Min RK <notifications@github.com> wrote:

> Who should "I am" be referring to? A prospective hub-deployer? If so,
> here's a shot:
>
> I am: a teacher/professor with linux admin skills or a student assistant /
> campus support with such skills.
> I am trying to: teach a scientific subject with computational work
> But: Dealing with software problems on diverse student computers consumes
> too much time
> Because: There are lots of different kinds of computers and ways to
> install things and many versions of everything
> Which makes me feel: 🐌 (I don't know how to deal with this one)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/94#issuecomment-222619596>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0PTJCT-i7i9b7WEKylV8bY4nVM5Eks5qG-wlgaJpZM4IqGLh>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
OK here is an initial user test of JupyterHub content on the website:

http://www.usertesting.com/videos/Mak-g9WxfhQWYxtPbLqe-w?shared=true

Very worth watching!!! @willingc @minrk @fperez

**Comment by ellisonbg** [comment]
I am running another one, with the same tasks, but a bit more clarification up front about JupyterHub and Jupyter being different.

**Comment by fperez** [comment]
Just saw the video, thanks!

**Comment by willingc** [comment]
Actual personas from PyCon

**Manager of a team of analysts in a business setting**
I am: the manager of a team of analysts responsible for analysis, reports, and business metrics
I am trying to: teach my business analysts who are used to SAS, SPSS, some RStudio to use Python
But: they are struggling since they are not CS programmers and do not understand git, sw workflow, etc.
Because: I lack an easy way to get them started using Python analysis tools
Which makes me feel: frustrated, confused

**Professor of Social Science**
I am: a professor of social science wanting to teach students the notebook and Python libraries for analysis and visualization
I am trying to: provide a simple way for students who are not programmers nor do most wish to be
Because: I lack an easy way to get them started
Which makes me feel: confused

**Comment by ellisonbg** [comment]
@willingc thanks, that is super helpful!

Some take aways in your personas:

* For the "manager of a team of analysts" persona, it sounds like being able to shield those users from the pain of installation is a huge benefit of JupyterHub. Sure, it may be painful for the person that installs JuptyerHub (we can ease this too), but for the manager who is evaluating JupyterHub, it is a huge selling point that their end users (the team) are completely shielded from the deployment/installation challenges.
* Based on this, I think the JupyterHub docs and webpage should distinguish between the challenges of deploying JupyterHub and the pleasant experience for users once that is done.
* Also, for both of these personas, it seems like the easy of installation (none, for users), is only one parts of what would make those users experience nice.

**Comment by fperez** [comment]
On Wed, Jun 1, 2016 at 3:15 PM, Brian E. Granger <notifications@github.com>
wrote:

> For the "manager of a team of analysts" persona, it sounds like being able
> to shield those users from the pain of installation is a huge benefit of
> JupyterHub. Sure, it may be painful for the person that installs JuptyerHub
> (we can ease this too), but for the manager who is evaluating JupyterHub,
> it is a huge selling point that their end users (the team) are completely
> shielded from the deployment/installation challenges.


I just had a discussion with Berkeley folks deploying JHub for data science
campus-wide, and they absolutely zoomed in on this factor as a *major*
advantage of JHub.  It does require some IT support, but it gives them full
and precise control over the environment the students have (versions,
libraries, content), with "just a browser" as the only requirement. In
courses with 500+ students, this is the difference between viable and
impossible deployment (if they were to do it locally for everyone).

Cheers

f


-- 
Fernando Perez (@fperez_org; http://fperez.org)
fperez.net-at-gmail: mailing lists only (I ignore this when swamped!)
fernando.perez-at-berkeley: contact me here for any direct mail

**Comment by choldgraf** [comment]
hey all - I was just thinking to myself "we really need a JupyterHub information page on the website" and came across this issue. It sounds like there was some user story-boarding, but did anything come of this issue?

I would be in favor of pushing this forward again, especially since JupyterHub now deploys on Kubernetes and there are multiple versions of documentation that call out to "JupyterHub", there'd be a lot of value in disambiguating.

> For example, I was chatting with a person from Stencila this morning, and he mentioned that he didn't think to use JupyterHub because he never realized that it could run on Kubernetes. He had seen the phrase "Zero to JupyterHub", but that wasn't enough to get him to click on the docs since it didn't say K8S. 

If there were a landing page that could give a high-level view of all the stuff JupyterHub can do (and if this page ideally showed up first in google searches), that'd be quite helpful.

Are people OK with me putting together a draft of a page such as this?

**Comment by ellisonbg** [comment]
Sure! I would at least coordinate with @tgeorgeux and @jzf2101 as they are working on a larger refactor.

**Comment by jzf2101** [comment]
Yes! We are

**Comment by choldgraf** [comment]
in my mind, this would be a short-term content add with pretty much no changes to style etc. IMO having the content we want up there is more important than the design or layout. I'll put together a quick PR and we can always repurpose the page wording when the refactor lands.

**Comment by choldgraf** [comment]
This is now merged in #297

**Comment by choldgraf** [comment]
(but I don't apparently have the rights to close this issue)
